"""add user_uasgs table

Revision ID: b6d0ac4d7054
Revises: 598879ac5e33
Create Date: 2026-04-23 04:58:06.230893+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'b6d0ac4d7054'
down_revision = '598879ac5e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_uasgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('codigo_uasg', sa.String(length=10), nullable=False),
    sa.Column('nome_uasg', sa.String(length=200), nullable=True),
    sa.Column('sigla_uf', sa.String(length=2), nullable=True),
    sa.Column('nome_municipio', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'codigo_uasg', name='uq_user_uasg')
    )
    op.create_index(op.f('ix_user_uasgs_user_id'), 'user_uasgs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uasgs_user_id'), table_name='user_uasgs')
    op.drop_table('user_uasgs')
    # ### end Alembic commands ###
