"""add uasg arp items empenhos tables

Revision ID: 9046405588ca
Revises: afc54c4add70
Create Date: 2026-04-23 05:16:56.428252+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9046405588ca'
down_revision = 'afc54c4add70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uasg_id', sa.Integer(), nullable=False),
    sa.Column('numero_controle_pncp_ata', sa.String(length=100), nullable=False),
    sa.Column('numero_ata_registro_preco', sa.String(length=100), nullable=True),
    sa.Column('data_vigencia_inicial', sa.Date(), nullable=True),
    sa.Column('data_vigencia_final', sa.Date(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uasg_id'], ['user_uasgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uasg_id', 'numero_controle_pncp_ata', name='uq_user_arp')
    )
    op.create_index(op.f('ix_arps_numero_controle_pncp_ata'), 'arps', ['numero_controle_pncp_ata'], unique=False)
    op.create_index(op.f('ix_arps_user_uasg_id'), 'arps', ['user_uasg_id'], unique=False)
    op.create_table('arp_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arp_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['arp_id'], ['arps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arp_id', 'numero_item', name='uq_arp_item')
    )
    op.create_index(op.f('ix_arp_items_arp_id'), 'arp_items', ['arp_id'], unique=False)
    op.create_table('arp_empenhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arp_item_id', sa.Integer(), nullable=False),
    sa.Column('numero_empenho', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['arp_item_id'], ['arp_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arp_empenhos_arp_item_id'), 'arp_empenhos', ['arp_item_id'], unique=False)
    op.add_column('user_uasgs', sa.Column('sync_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('user_uasgs', sa.Column('sync_error', sa.Text(), nullable=True))
    op.add_column('user_uasgs', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_uasgs', sa.Column('last_arp_count', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uasgs', 'last_arp_count')
    op.drop_column('user_uasgs', 'synced_at')
    op.drop_column('user_uasgs', 'sync_error')
    op.drop_column('user_uasgs', 'sync_status')
    op.drop_index(op.f('ix_arp_empenhos_arp_item_id'), table_name='arp_empenhos')
    op.drop_table('arp_empenhos')
    op.drop_index(op.f('ix_arp_items_arp_id'), table_name='arp_items')
    op.drop_table('arp_items')
    op.drop_index(op.f('ix_arps_user_uasg_id'), table_name='arps')
    op.drop_index(op.f('ix_arps_numero_controle_pncp_ata'), table_name='arps')
    op.drop_table('arps')
    # ### end Alembic commands ###
