"""add uasg arp items empenhos tables

Revision ID: afc54c4add70
Revises: b6d0ac4d7054
Create Date: 2026-04-23 05:15:26.586121+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'afc54c4add70'
down_revision = 'b6d0ac4d7054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
